#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot whell joints
whell_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Rueda_izquierda_del_joint, Rueda_derecha_del_joint, Rueda_izquierda_tras_joint, Rueda_derecha_tras_joint]

#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Waist_joint, Shoulder_joint, Elbow_joint, Wrist_Roll_joint, Wrist_pitch_joint]

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Left_gear_joint, Rigth_gear_joint]
# Rigth_gear_joint
#[Left_gear_joint, Left_arm_joint, Rigth_gear_joint, Right_arm_joint, Left_Link_joint, Rigth_Link_joint]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
