controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - Waist_joint
      - Shoulder_joint
      - Elbow_joint
      - Wrist_Roll_joint
      - Wrist_pitch_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - Left_Link_joint
      - Left_gear_joint
      - Left_arm_joint
      - Rigth_Link_joint
      - Rigth_gear_joint
      - Right_arm_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home
  - group: gripper
    pose: g_close