#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController
controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - Waist_joint
    - Shoulder_joint
    - Elbow_joint
    - Wrist_Roll_joint
    - Wrist_pitch_joint
  - name: gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - Left_gear_joint
    - Left_arm_joint
    - Rigth_gear_joint
    - Right_arm_joint
    - Left_Link_joint
    - Rigth_Link_joint
    