# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gripper
  joint_model_group_pose: g_open
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Rueda_derecha_del_joint
    - Rueda_derecha_tras_joint
    - Rueda_izquierda_del_joint
    - Rueda_izquierda_tras_joint
    - Waist_joint
    - Shoulder_joint
    - Elbow_joint
    - Wrist_Roll_joint
    - Wrist_pitch_joint
    - Left_gear_joint
    - Rigth_gear_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []